// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcG6H_9HWX65mT5fsfDXJLJ4oD1fAJdAk',
    appId: '1:520772632002:web:aea680129050a0ddc5ea5b',
    messagingSenderId: '520772632002',
    projectId: 'calculator-83f26',
    authDomain: 'calculator-83f26.firebaseapp.com',
    storageBucket: 'calculator-83f26.appspot.com',
    measurementId: 'G-KXHTHNW7J0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd1TzphSkzZOx4-BGYtR4p0iJVMfTI2rc',
    appId: '1:520772632002:android:308ee50846f91f41c5ea5b',
    messagingSenderId: '520772632002',
    projectId: 'calculator-83f26',
    storageBucket: 'calculator-83f26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXgi94cdmYosJXPqtWPWq0UlxfLFz3BEA',
    appId: '1:520772632002:ios:b6f6f33e76effe39c5ea5b',
    messagingSenderId: '520772632002',
    projectId: 'calculator-83f26',
    storageBucket: 'calculator-83f26.appspot.com',
    iosBundleId: 'com.example.calculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXgi94cdmYosJXPqtWPWq0UlxfLFz3BEA',
    appId: '1:520772632002:ios:b6f6f33e76effe39c5ea5b',
    messagingSenderId: '520772632002',
    projectId: 'calculator-83f26',
    storageBucket: 'calculator-83f26.appspot.com',
    iosBundleId: 'com.example.calculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcG6H_9HWX65mT5fsfDXJLJ4oD1fAJdAk',
    appId: '1:520772632002:web:062d58ba4306cc2dc5ea5b',
    messagingSenderId: '520772632002',
    projectId: 'calculator-83f26',
    authDomain: 'calculator-83f26.firebaseapp.com',
    storageBucket: 'calculator-83f26.appspot.com',
    measurementId: 'G-NNPDS1PL2K',
  );
}
